apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregated-manager-role
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        capv.infrastucture.cluster.x-k8s.io/aggregate-to-manager: "true"
rules: []
